# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- checkout: self
- task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@3
  displayName: Run CredScan
  inputs:
    outputFormat: sarif
    debugMode: false
    folderSuppression: false
- task: PoliCheck@1
  displayName: Run PoliCheck
  inputs:
    targetArgument: $(Build.SourcesDirectory)
    result: $(Build.SourcesDirectory)/artifacts/result/PoliCheck.xml
- task: PublishPipelineArtifact@0
  displayName: Save artifacts
  inputs:
    artifactName: artifacts
    targetPath: artifacts
